In [1]:
6+5

11

In [2]:
x = 5
y = 6

print(x+y)

11


In [4]:
def add(x, y):
    return x+y


add(5, 6)

11

In [3]:
def add(x, y, z=None):
    if z==None:
        return x+y
    else:
        return x+y+z

add(1,2)

3

In [8]:
l = [1, 'a', 5, '8']

print(len(l))

for i in l:
    print(i)
    
1 in l

4
1
a
5
8


True

In [11]:
s = 'sayem sayed'

s = s.split()[-1]

print(s)

sayed


In [17]:
d = {1: 'sayem', 2: 'sayed'}

print(d[1])

d[3] = 'munnni'

for i,j in d.items():
    print(i,j)

sayem
1 sayem
2 sayed
3 munnni


In [22]:
s = input()

l = s.split()

a, b, c = l

print(a, b, c)

1 2 3
1 2 3


In [24]:
a = 12346
s = 'sayem = '

print(s + str(a))

sayem = 12346


In [27]:
#Data files and Summary statistics

In [2]:
import csv

%precision 2

with open ('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:1]

[OrderedDict([('age', '63'),
              ('sex', '1'),
              ('cp', '1'),
              ('trestbps', '145'),
              ('chol', '233'),
              ('fbs', '1'),
              ('restecg', '2'),
              ('thalach', '150'),
              ('exang', '0'),
              ('oldpeak', '2.3'),
              ('slope', '3'),
              ('ca', '0'),
              ('thal', '6'),
              ('target', '0')])]

In [34]:
len(mpg)

298

In [3]:
mpg[5].keys()

odict_keys(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'])

In [36]:
sum(float(d['chol']) for d in mpg)/len(mpg)

247.15

In [37]:
ls = set(d['age'] for d in mpg)

print(ls)

{'37', '59', '46', '68', '39', '53', '60', '40', '74', '64', '71', '61', '48', '29', '42', '51', '67', '50', '47', '55', '77', '76', '57', '38', '52', '70', '63', '54', '49', '43', '44', '62', '41', '65', '56', '45', '58', '35', '69', '66', '34'}


In [38]:
v = []

for l in ls:
    cn = 0
    total = 0
    
    for d in mpg:
        if(d['age']==l):
            total += float(d['cp'])
            cn += 1
    v.append((l, total/cn))

v.sort(key = lambda x:x[0])

print(v)

[('29', 2.0), ('34', 1.5), ('35', 3.5), ('37', 3.0), ('38', 1.0), ('39', 3.25), ('40', 3.0), ('41', 2.5), ('42', 3.0), ('43', 3.7142857142857144), ('44', 3.0), ('45', 2.875), ('46', 3.142857142857143), ('47', 3.4), ('48', 3.142857142857143), ('49', 2.8), ('50', 3.2857142857142856), ('51', 3.1666666666666665), ('52', 2.8333333333333335), ('53', 3.7142857142857144), ('54', 3.1875), ('55', 3.25), ('56', 2.909090909090909), ('57', 3.5625), ('58', 3.263157894736842), ('59', 2.857142857142857), ('60', 3.5), ('61', 3.5), ('62', 3.4545454545454546), ('63', 3.3333333333333335), ('64', 3.1), ('65', 3.25), ('66', 3.142857142857143), ('67', 3.6666666666666665), ('68', 3.25), ('69', 1.6666666666666667), ('70', 3.25), ('71', 3.0), ('74', 2.0), ('76', 3.0), ('77', 4.0)]


In [39]:
l = [1, 2, 3, 4]

sq = lambda num : num**2

lst = list(map(sq, l))

print(lst)

for i in map(sq, l):
    print(i)

[1, 4, 9, 16]
1
4
9
16


In [60]:
import datetime as dt
import time as tm

tm.time()

1587375681.5617573

In [61]:
dtnow = dt.datetime.fromtimestamp(tm.time())

print(dtnow)

print(dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second)

delta = dt.timedelta(days = 100)
today = dt.date.today()

print(delta)
print(today)
print(today-delta)

2020-04-20 15:55:04.531380
2020 4 20 15 55 4
100 days, 0:00:00
2020-04-20
2020-01-11


In [65]:
class Person:
    department = 'CSE'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [76]:
s1 = [10, 11, 12, 2, 1]
s2 = [9, 25, 12, 5, 4]

cheap = list(map(min, s1, s2))

print(cheap)

[9, 11, 12, 2, 1]


In [101]:
func = lambda a, b, c : a+b

print(func(5, 6, 7))

s = "sayem"

f = lambda s: s[0]

print(f(s))

11
s


In [121]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    f = lambda x:x.split()[0]+' '+x.split()[-1]
    
    print(split_title_and_name(person) == f(person))
    
    print(split_title_and_name(person) == (lambda x:x.split()[0]+' '+x.split()[-1])(person))
    
# option 2
list(map(split_title_and_name, people)) == list(map(lambda x:x.split()[0]+' '+x.split()[-1],people))

True
True
True
True
True
True
True
True


True

In [123]:
l = [i for i in range(0, 20) if i % 2 ==0]

print(l)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [131]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [i*j for i in range(10) for j in range(10)]

True

In [1]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [i+j+k+k for i in lowercase for j in lowercase for k in digits for l in digits]

print(answer)

['aa00', 'aa00', 'aa00', 'aa00', 'aa00', 'aa00', 'aa00', 'aa00', 'aa00', 'aa00', 'aa11', 'aa11', 'aa11', 'aa11', 'aa11', 'aa11', 'aa11', 'aa11', 'aa11', 'aa11', 'aa22', 'aa22', 'aa22', 'aa22', 'aa22', 'aa22', 'aa22', 'aa22', 'aa22', 'aa22', 'aa33', 'aa33', 'aa33', 'aa33', 'aa33', 'aa33', 'aa33', 'aa33', 'aa33', 'aa33', 'aa44', 'aa44', 'aa44', 'aa44', 'aa44', 'aa44', 'aa44', 'aa44', 'aa44', 'aa44', 'aa55', 'aa55', 'aa55', 'aa55', 'aa55', 'aa55', 'aa55', 'aa55', 'aa55', 'aa55', 'aa66', 'aa66', 'aa66', 'aa66', 'aa66', 'aa66', 'aa66', 'aa66', 'aa66', 'aa66', 'aa77', 'aa77', 'aa77', 'aa77', 'aa77', 'aa77', 'aa77', 'aa77', 'aa77', 'aa77', 'aa88', 'aa88', 'aa88', 'aa88', 'aa88', 'aa88', 'aa88', 'aa88', 'aa88', 'aa88', 'aa99', 'aa99', 'aa99', 'aa99', 'aa99', 'aa99', 'aa99', 'aa99', 'aa99', 'aa99', 'ab00', 'ab00', 'ab00', 'ab00', 'ab00', 'ab00', 'ab00', 'ab00', 'ab00', 'ab00', 'ab11', 'ab11', 'ab11', 'ab11', 'ab11', 'ab11', 'ab11', 'ab11', 'ab11', 'ab11', 'ab22', 'ab22', 'ab22', 'ab22', 'ab22',

In [5]:
# Numpy

import numpy as np

In [38]:
l = [1, 2, 3]

a = np.array(l)
x = np.array([1, 2, 3])

print(a)
print(x, '\n')

m = np.array([[1, 2, 3], [4, 5, 6]])

print(m)
print(m.shape, '\n')

m = np.arange(0, 30, 2)

print(m, '\n')

m = m.reshape(3, 5)

print(m, '\n')

m = np.linspace(0, 4, 9)

print(m)

m = m.reshape(3, 3)

print(m)

[1 2 3]
[1 2 3] 

[[1 2 3]
 [4 5 6]]
(2, 3) 

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28] 

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]] 

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [59]:
y = [4, 5, 6, 7]

m = np.ones((3, 3))
print(m, '\n')

m = np.zeros((3, 3))
print(m, '\n')

m = np.eye(3)
print(m, '\n')

m = np.diag(y)
print(m, '\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]] 



In [7]:
m = np.array([1, 2, 3] * 3)
print(m, '\n')

m = np.repeat([1, 2, 3], 3)
print(m, '\n')

m = np.ones((2, 3), int)
print(m, '\n')
m = np.vstack((m, 2*m))
print(m, '\n')

m = np.ones([2, 3], int)
m = np.hstack((m, 2*m))
print(m)

[1 2 3 1 2 3 1 2 3] 

[1 1 1 2 2 2 3 3 3] 

[[1 1 1]
 [1 1 1]] 

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]] 

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


In [92]:
x = [1, 2, 3]
x = np.array(x)

y = [4, 5, 6]
y = np.array(y)

print(x+y)
print(x*y)
print(x**2)
print(x.dot(y), '\n')

z = np.array([y, y**2])
print(z)
z = z.T
print(z)
print(z.dtype)

z = z.astype('f') #type casting
print(z.dtype)

[5 7 9]
[ 4 10 18]
[1 4 9]
32 

[[ 4  5  6]
 [16 25 36]]
[[ 4 16]
 [ 5 25]
 [ 6 36]]
int32
float32


In [95]:
a = np.array([-4, -2, 1, 3, 5])

print(a.sum())
print(a.max())
print(a.min())
print(a.mean())
print(a.std())
print(a.argmax()) #index of maximim
print(a.argmin())

3
5
-4
0.6
3.2619012860600183
4
0


In [105]:
a = np.arange(13)**2

print(a)

print(a[1:4])
print(a[-4:])
print(a[-5::-2])

[  0   1   4   9  16  25  36  49  64  81 100 121 144]
[1 4 9]
[ 81 100 121 144]
[64 36 16  4  0]


In [9]:
r = np.arange(36)
r = r.reshape((6, 6))

print(r)
print(r[2, 3])
print(r[3, 2:5])
print(r[:2, :-1])
print(r[-1, ::2])
print(r[r>4], '\n')

r[r>30] = 30

print(r)

r = r.reshape(36)[::7]

r

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
15
[20 21 22]
[[ 0  1  2  3  4]
 [ 6  7  8  9 10]]
[30 32 34]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


array([ 0,  7, 14, 21, 28, 30])

In [150]:
r1 = r[:3, :3] #assign korte change hoe jay
print(r1, '\n')

r1[:] = 0

print(r1, '\n')
print(r, '\n') #r is changed also

r_copy = r.copy()
r_copy[:] = 10

print(r_copy, '\n')
print(r)#r is not changed

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]] 

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [152]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [171]:
test = np.random.randint(0, 10, (4, 3))

print(test, '\n')

for r in test:
    print(r)
print()

for i in range(len(test)):
    print(test[i])
print()

for i, r in enumerate(test):
    print(i, ' = ', r)
    
test2 = test**2

print(test2)

for i, j in zip(test, test2):
    print(i, ' + ', j, ' = ', i+j)

[[8 3 4]
 [6 9 7]
 [1 5 3]
 [1 5 5]] 

[8 3 4]
[6 9 7]
[1 5 3]
[1 5 5]

[8 3 4]
[6 9 7]
[1 5 3]
[1 5 5]

0  =  [8 3 4]
1  =  [6 9 7]
2  =  [1 5 3]
3  =  [1 5 5]
[[64  9 16]
 [36 81 49]
 [ 1 25  9]
 [ 1 25 25]]
[8 3 4]  +  [64  9 16]  =  [72 12 20]
[6 9 7]  +  [36 81 49]  =  [42 90 56]
[1 5 3]  +  [ 1 25  9]  =  [ 2 30 12]
[1 5 5]  +  [ 1 25 25]  =  [ 2 30 30]
